version: '3'

services:
  database:
    env_file: .env
    image: postgres:14-alpine
    container_name: "database"
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - data-volume:/var/lib/db_data
    networks:
      - todo-network

  adminer:
    image: adminer
    container_name: "adminer"
    restart: always
    ports:
      - 8080:8080
    networks:
      - todo-network

  todo:
    build: .
    container_name: "todo"
    env_file: .env
    ports:
      - "80:80"
    networks:
      - todo-network


volumes:
  data-volume:

networks:
  todo-network:
    driver: bridge
