services:
  db:
    env_file: .env
    image: postgres:14-alpine
    container_name: "database"
    ports:
      - "5432:5432"
    volumes:
      - data-volume:/var/lib/db_data

volumes:
  data-volume:
