"""test

Revision ID: 6e3250e710d7
Revises: 44a330c15646
Create Date: 2022-05-31 12:37:55.677761+00:00

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6e3250e710d7"
down_revision = "44a330c15646"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("account")
    op.drop_index("ix_tests_description", table_name="tests")
    op.drop_index("ix_tests_id", table_name="tests")
    op.drop_table("tests")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tests",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="tests_pkey"),
    )
    op.create_index("ix_tests_id", "tests", ["id"], unique=False)
    op.create_index("ix_tests_description", "tests", ["description"], unique=False)
    op.create_table(
        "account",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column(
            "description", sa.VARCHAR(length=200), autoincrement=False, nullable=True
        ),
        sa.Column(
            "last_transaction_date",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="account_pkey"),
    )
    # ### end Alembic commands ###
